highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
#paginate: 5
port: 4000
safe: true
url: http://mr-karan.github.io/resume
author: Karan Sharma

baseurl: /resume/
title: Karan Sharma's Resume
name: Karan Sharma
email: karansharma1295@gmail.com
email_full: mailto:karansharma1295@gmail.com
website: mr-karan.github.io
github: mr-karan
twitter: mrkaran_
tel: +91 9650 318721
tel_full: tel:+919650318721

